pref("extensions.zotero.stylepersonal.enable", true);
pref("extensions.zotero.stylepersonal.function.dateAddedColumn.enable", true);
pref("extensions.zotero.stylepersonal.dateAddedColumn.dateType", "absolute");
pref("extensions.zotero.stylepersonal.dateAddedColumn.format", "YYYY/M/D H:m:s");
pref("extensions.zotero.stylepersonal.dateAddedColumn.deltaHour", "system");
pref("extensions.zotero.stylepersonal.dateModifiedColumn.dateType", "absolute");
pref("extensions.zotero.stylepersonal.dateModifiedColumn.format", "YYYY/M/D H:m:s");
pref("extensions.zotero.stylepersonal.dateModifiedColumn.deltaHour", "system");
pref("extensions.zotero.stylepersonal.function.favoriteCollections.enable", true);
pref("extensions.zotero.stylepersonal.function.tldr.enable", false);
pref("extensions.zotero.stylepersonal.tldr.autoTranslate", false);
pref("extensions.zotero.stylepersonal.function.toogleSidebar.enable", true);
pref("extensions.zotero.stylepersonal.toogleSidebar.left.shortcut", "Shift + {");
pref("extensions.zotero.stylepersonal.toogleSidebar.right.shortcut", "Shift + }");
pref("extensions.zotero.stylepersonal.function.styleEditor.enable", false);
pref("extensions.zotero.stylepersonal.styleEditor.value", ".view-popup .tool-toggle {display: none;}");
pref("extensions.zotero.stylepersonal.function.updateItemDateModified.enable", true);
pref("extensions.zotero.stylepersonal.function.addTags.enable", true);
pref("extensions.zotero.stylepersonal.addTags.shortcut", "Ctrl + T");
pref("extensions.zotero.stylepersonal.titleTranslate.shortcut", "Ctrl + Alt + T");
pref("extensions.zotero.stylepersonal.function.relatedItems.enable", true);
pref("extensions.zotero.stylepersonal.relatedItems.link.shortcut", "Alt + L");
pref("extensions.zotero.stylepersonal.recordInterval", 10);
pref("extensions.zotero.stylepersonal.function.graphView.enable", true);
pref("extensions.zotero.stylepersonal.graphView.enable", false);
pref("extensions.zotero.stylepersonal.graphView.height", "400px");
pref("extensions.zotero.stylepersonal.graphView.mode", "citations");
pref("extensions.zotero.stylepersonal.graphView.modes.citations", true);
pref("extensions.zotero.stylepersonal.graphView.modes.note", true);
pref("extensions.zotero.stylepersonal.graphView.modes.author", true);
pref("extensions.zotero.stylepersonal.graphView.modes.tag", true);
pref("extensions.zotero.stylepersonal.graphView.modes.genealogy", true);
pref("extensions.zotero.stylepersonal.citations.onAdd", "ask");
pref("extensions.zotero.stylepersonal.citations.onEmpty", "ask");
pref("extensions.zotero.stylepersonal.function.tagsColumn.enable", true);
pref("extensions.zotero.stylepersonal.tagsColumn.margin", "0.15");
pref("extensions.zotero.stylepersonal.tagsColumn.align", "left");
pref("extensions.zotero.stylepersonal.function.textTagsColumn.enable", true);
pref("extensions.zotero.stylepersonal.textTagsColumn.match", "/^#(?:.+/)*(.+)/");
pref("extensions.zotero.stylepersonal.textTagsColumn.opacity", "0.13");
pref("extensions.zotero.stylepersonal.textTagsColumn.backgroundColor", "#8e44ad");
pref("extensions.zotero.stylepersonal.textTagsColumn.textColor", "auto");
pref("extensions.zotero.stylepersonal.textTagsColumn.margin", "0.2");
pref("extensions.zotero.stylepersonal.textTagsColumn.padding", "0.5");
pref("extensions.zotero.stylepersonal.function.titleColumn.enable", true);
pref("extensions.zotero.stylepersonal.titleColumn.color", "#FFC6D3");
pref("extensions.zotero.stylepersonal.titleColumn.tags", false);
pref("extensions.zotero.stylepersonal.titleColumn.emojiTags", false);
pref("extensions.zotero.stylepersonal.titleColumn.opacity", "0.7");
pref("extensions.zotero.stylepersonal.titleColumn.translate", false);
pref("extensions.zotero.stylepersonal.function.IFColumn.enable", true);
pref("extensions.zotero.stylepersonal.IFColumn.field", "sciif");
pref("extensions.zotero.stylepersonal.IFColumn.text", true);
pref("extensions.zotero.stylepersonal.IFColumn.progress", true);
pref("extensions.zotero.stylepersonal.IFColumn.color", "#41a1a2");
pref("extensions.zotero.stylepersonal.IFColumn.opacity", "1");
pref("extensions.zotero.stylepersonal.IFColumn.max", "15");
pref("extensions.zotero.stylepersonal.IFColumn.progressType", "2");
pref("extensions.zotero.stylepersonal.function.publicationTagsColumn.enable", true);
pref("extensions.zotero.stylepersonal.publicationTagsColumn.fields", "sciif, sci, utd24, sciBase, ssci, pku, 复合影响因子");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.rankColors", "#ffe2dd, #e8deee, #dbeddb, #fadec9, #e9e8e7");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.defaultColor", "#86dad1");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.textColor", "auto");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.sortBy", "sci, -sciif");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.map", "北大中文核心=北核, SCIIF=IF, SCIIF(5)=IF(5), SCI基础版=中科院");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.margin", "0.08");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.padding", "0.455");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.opacity", "1");
pref("extensions.zotero.stylepersonal.function.annotationColumn.enable", true);
pref("extensions.zotero.stylepersonal.annotationColumn.opacity", "0.7");
pref("extensions.zotero.stylepersonal.function.ratingColumn.enable", true);
pref("extensions.zotero.stylepersonal.ratingColumn.storage", "extra");
pref("extensions.zotero.stylepersonal.ratingColumn.selectedStar", "⭐");
pref("extensions.zotero.stylepersonal.ratingColumn.unselectedStar", "🌙");
pref("extensions.zotero.stylepersonal.ratingColumn.padding", "2");
pref("extensions.zotero.stylepersonal.function.viewManager.enable", true);
pref("extensions.zotero.stylepersonal.viewGroups", "[]");
pref("extensions.zotero.stylepersonal.function.showAnnotationColorName.enable", false);
pref("extensions.zotero.stylepersonal.annotationColorNameDirection", "horizontal");
pref("extensions.zotero.stylepersonal.function.annotationColors.enable", true);
pref("extensions.zotero.stylepersonal.annotationColors", "[[\"general.yellow\",\"#ffd400\"],[\"general.red\",\"#ff6666\"],[\"general.green\",\"#5fb236\"],[\"general.blue\",\"#2ea8e5\"],[\"general.purple\",\"#a28ae5\"],[\"general.magenta\",\"#e56eee\"],[\"general.orange\",\"#f19837\"],[\"general.gray\",\"#aaaaaa\"]]");
pref("extensions.zotero.stylepersonal.annotationColorsGroups", "[[\"Untitled\",[[\"general.yellow\",\"#ffd400\"],[\"general.red\",\"#ff6666\"],[\"general.green\",\"#5fb236\"],[\"general.blue\",\"#2ea8e5\"],[\"general.purple\",\"#a28ae5\"],[\"general.magenta\",\"#e56eee\"],[\"general.orange\",\"#f19837\"],[\"general.gray\",\"#aaaaaa\"]]]]");
pref("extensions.zotero.stylepersonal.function.collectionItemCount.enable", true);
pref("extensions.zotero.stylepersonal.function.sortCollectionItem.enable", true);
pref("extensions.zotero.stylepersonal.collectionItem.sortBy", "");
pref("extensions.zotero.stylepersonal.function.tags.enable", true);
pref("extensions.zotero.stylepersonal.function.creatorColumn.enable", false);
pref("extensions.zotero.stylepersonal.creatorColumn.format", "${firstName} ${lastName}");
pref("extensions.zotero.stylepersonal.creatorColumn.slices", "0:1");
pref("extensions.zotero.stylepersonal.creatorColumn.join", ", ");
pref("extensions.zotero.stylepersonal.function.publicationColumn.enable", true);
pref("extensions.zotero.stylepersonal.publicationColumn.fields", "publicationTitle, conferenceName, university, publisher");
pref("extensions.zotero.stylepersonal.function.PDFStyles.enable", true);
pref("extensions.zotero.stylepersonal.storage.in", "file");
pref("extensions.zotero.stylepersonal.storage.filename", "style-personal");
pref("extensions.zotero.stylepersonal.readingProgress.recordingEnabled", false);
pref("extensions.zotero.stylepersonal.easyscholar.secretKey", "");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.source", "easyscholar");
pref("extensions.zotero.stylepersonal.garden.apiKey", "");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.gardenFields", "IF, JCI, JCR, 中科院 2025, CiteScore, 5YIF, 新锐");
pref("extensions.zotero.stylepersonal.function.readTimeColumn.enable", true);
pref("extensions.zotero.stylepersonal.readTime.color", "#468B97");
pref("extensions.zotero.stylepersonal.readTime.opacity", "0.7");
pref("extensions.zotero.stylepersonal.readTime.max", "600");
pref("extensions.zotero.stylepersonal.readTime.progress", true);
pref("extensions.zotero.stylepersonal.readTime.text", true);
pref("extensions.zotero.stylepersonal.function.remarkColumn.enable", true);
pref("extensions.zotero.stylepersonal.function.statusColumn.enable", true);
pref("extensions.zotero.stylepersonal.function.darkLightButton.enable", true);
pref("extensions.zotero.stylepersonal.function.reader.mergeAnnotations.enable", true);
pref("extensions.zotero.stylepersonal.function.reader.attachmentVersionSwitch.enable", true);
pref("extensions.zotero.stylepersonal.graphView.labelField", "authorYear");
pref("extensions.zotero.stylepersonal.graphView.extraLabelKey", "Graph Label");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.aliases", "{}");
pref("extensions.zotero.stylepersonal.function.manualJournalRanks.enable", true);
pref("extensions.zotero.stylepersonal.publicationTagsColumn.manualRanks", "{}");
pref("extensions.zotero.stylepersonal.publicationTagsColumn.automaticUpdates", true);
pref("extensions.zotero.stylepersonal.function.citationGraph.enable", true);
pref("extensions.zotero.stylepersonal.function.genealogy.enable", true);
pref("extensions.zotero.stylepersonal.genealogy.manualData", '{"version":1,"people":{},"relations":{}}');
pref("extensions.zotero.stylepersonal.graphView.scope", "selected");
pref("extensions.zotero.stylepersonal.graphView.depth", "1");
pref("extensions.zotero.stylepersonal.graphView.hideIsolated", false);
pref("extensions.zotero.stylepersonal.graphView.minYear", "");
pref("extensions.zotero.stylepersonal.graphView.maxYear", "");
pref("extensions.zotero.stylepersonal.function.tabMenu.enable", true);
pref("extensions.zotero.stylepersonal.function.fulltextTranslate.enable", true);
pref("extensions.zotero.stylepersonal.function.commands.enable", true);
pref("extensions.zotero.stylepersonal.function.prefsManager.enable", true);
pref("extensions.zotero.stylepersonal.function.addColorNameTag.enable", false);
