import { config } from '../config.ts';

export interface PreferenceValues {
  "enable": boolean;
  "function.menuVisibility.enable": boolean;
  "function.dateAddedColumn.enable": boolean;
  "dateAddedColumn.dateType": string;
  "dateAddedColumn.format": string;
  "dateAddedColumn.deltaHour": string;
  "dateModifiedColumn.dateType": string;
  "dateModifiedColumn.format": string;
  "dateModifiedColumn.deltaHour": string;
  "function.favoriteCollections.enable": boolean;
  "AIGenerateTags.prompt": string;
  "function.tldr.enable": boolean;
  "tldr.autoTranslate": boolean;
  "function.toogleSidebar.enable": boolean;
  "toogleSidebar.left.shortcut": string;
  "toogleSidebar.right.shortcut": string;
  "delayTime": number;
  "function.styleEditor.enable": boolean;
  "styleEditor.value": string;
  "function.updateItemDateModified.enable": boolean;
  "function.addTags.enable": boolean;
  "addTags.shortcut": string;
  "titleTranslate.shortcut": string;
  "function.relatedItems.enable": boolean;
  "relatedItems.link.shortcut": string;
  "recordInterval": number;
  "function.graphView.enable": boolean;
  "graphView.enable": boolean;
  "graphView.height": string;
  "graphView.mode": string;
  "graphView.modes.citations": boolean;
  "graphView.modes.note": boolean;
  "graphView.modes.author": boolean;
  "graphView.modes.tag": boolean;
  "graphView.modes.genealogy": boolean;
  "citations.onAdd": string;
  "citations.onEmpty": string;
  "graphView.show": boolean;
  "graphView.theme": string;
  "cookies.cnki": string;
  "function.tagsColumn.enable": boolean;
  "tagsColumn.margin": string;
  "tagsColumn.align": string;
  "function.textTagsColumn.enable": boolean;
  "textTagsColumn.prefix": string;
  "textTagsColumn.match": string;
  "textTagsColumn.opacity": string;
  "textTagsColumn.backgroundColor": string;
  "textTagsColumn.textColor": string;
  "textTagsColumn.margin": string;
  "textTagsColumn.padding": string;
  "function.titleColumn.enable": boolean;
  "titleColumn.color": string;
  "titleColumn.tags": boolean;
  "titleColumn.emojiTags": boolean;
  "titleColumn.opacity": string;
  "titleColumn.odd": string;
  "titleColumn.even": string;
  "titleColumn.selected": string;
  "titleColumn.translate": boolean;
  "function.IFColumn.enable": boolean;
  "IFColumn.field": string;
  "IFColumn.text": boolean;
  "IFColumn.progress": boolean;
  "IFColumn.color": string;
  "IFColumn.opacity": string;
  "IFColumn.max": string;
  "IFColumn.progressType": string;
  "IFColumn.info": boolean;
  "function.readStatus.enable": boolean;
  "function.publicationTagsColumn.enable": boolean;
  "publicationTagsColumn.fields": string;
  "publicationTagsColumn.rankColors": string;
  "publicationTagsColumn.defaultColor": string;
  "publicationTagsColumn.textColor": string;
  "publicationTagsColumn.sortBy": string;
  "publicationTagsColumn.map": string;
  "publicationTagsColumn.margin": string;
  "publicationTagsColumn.padding": string;
  "publicationTagsColumn.opacity": string;
  "function.annotationColumn.enable": boolean;
  "annotationColumn.style": string;
  "annotationColumn.color": string;
  "annotationColumn.opacity": string;
  "annotationColumn.circle": boolean;
  "function.ratingColumn.enable": boolean;
  "ratingColumn.storage": string;
  "ratingColumn.selectedStar": string;
  "ratingColumn.unselectedStar": string;
  "ratingColumn.padding": string;
  "function.viewManager.enable": boolean;
  "viewGroups": string;
  "function.showAnnotationColorName.enable": boolean;
  "annotationColorNameDirection": string;
  "function.annotationColors.enable": boolean;
  "annotationColors": string;
  "annotationColorsGroups": string;
  "function.itemTypeFilter.enable": boolean;
  "function.collectionItemCount.enable": boolean;
  "function.sortCollectionItem.enable": boolean;
  "collectionItem.sortBy": string;
  "function.tags.enable": boolean;
  "function.creatorColumn.enable": boolean;
  "creatorColumn.format": string;
  "creatorColumn.slices": string;
  "creatorColumn.join": string;
  "function.publicationColumn.enable": boolean;
  "publicationColumn.fields": string;
  "nestedTags.sortord": string;
  "nestedTags.linkSymbol": string;
  "function.PDFStyles.enable": boolean;
  "function.renderItemAnnotations.enable": boolean;
  "function.renderItemNotes.enable": boolean;
  "storage.in": string;
  "storage.filename": string;
  "readingProgress.recordingEnabled": boolean;
  "easyscholar.secretKey": string;
  "publicationTagsColumn.source": string;
  "garden.apiKey": string;
  "publicationTagsColumn.gardenFields": string;
  "function.Recent.enable": boolean;
  "function.ReadUnreadStatus.enable": boolean;
  "function.readTimeColumn.enable": boolean;
  "readTime.color": string;
  "readTime.opacity": string;
  "readTime.max": string;
  "readTime.progress": boolean;
  "readTime.text": boolean;
  "function.remarkColumn.enable": boolean;
  "remarkColumn.prompt": string;
  "function.statusColumn.enable": boolean;
  "function.darkLightButton.enable": boolean;
  "function.reader.mergeAnnotations.enable": boolean;
  "function.reader.attachmentVersionSwitch.enable": boolean;
  "graphView.labelField": string;
  "graphView.extraLabelKey": string;
  "publicationTagsColumn.aliases": string;
  "function.manualJournalRanks.enable": boolean;
  "publicationTagsColumn.manualRanks": string;
  "publicationTagsColumn.automaticUpdates": boolean;
  "function.citationGraph.enable": boolean;
  "function.genealogy.enable": boolean;
  "genealogy.manualData": string;
  "graphView.scope": string;
  "graphView.depth": string;
  "graphView.hideIsolated": boolean;
  "graphView.minYear": string;
  "graphView.maxYear": string;
  "function.tabMenu.enable": boolean;
  "function.fulltextTranslate.enable": boolean;
  "function.commands.enable": boolean;
  "function.prefsManager.enable": boolean;
  "function.addColorNameTag.enable": boolean;
}
export type PreferenceValue = string | number | boolean;
export function getPref<K extends keyof PreferenceValues>(key: K): PreferenceValues[K];
export function getPref(key: string): PreferenceValue;
export function getPref(key: string): PreferenceValue {
  return Zotero.Prefs.get(`${config.prefsPrefix}.${key}`, true);
}
export function setPref<K extends keyof PreferenceValues>(key: K, value: PreferenceValues[K]): void;
export function setPref(key: string, value: PreferenceValue): void;
export function setPref(key: string, value: PreferenceValue): void {
  Zotero.Prefs.set(`${config.prefsPrefix}.${key}`, value, true);
}
export function clearPref(key: string): void {
  Zotero.Prefs.clear(`${config.prefsPrefix}.${key}`, true);
}
